example/nightwatch.conf.js, example/package.json, example/yarn.lock
Use npm modules instead of linux only binaries.
=> Make it work on OSX

example/tests/groupA/basicTest.js, example/yarn.lock, src/commands/captureElementScreenshot.js
- Removed file format from captureElementScreenshot function call params. This is now handled by the generateFilename function to ensure consistent file format outputs.
- Implemented generateFilename function to create filenames in specified directory with pre-determined file naming structure and defined file format to output as (.png)
=> Implement filename generator function

src/reporting/views/index.handlebars
Allows you to show only passed, errors or failures.
=> TT-187 - add filter buttons to header

README.md, dist/assertions/elementRegresses.js, dist/commands/captureElementScreenshot.js, dist/index.js, dist/reporting/reporter.js, dist/reporting/server.js, dist/reporting/views/index.handlebars, example/globals.js, example/package.json, example/yarn.lock, src/commands/captureElementScreenshot.js, src/index.js, src/reporting/reporter.js, src/reporting/server.js, src/reporting/views/index.handlebars
Dropped report prompt, now will open if configured to do so,
documentation updated to include new report configuation options.
Report will terminate it's server on page close.
Noticed on Mac devices that captured images have the wrong dimensions,
have added the necessary changes to determine devicePixelRatio and
modify dimensions by that factor.
=> Documentation and fixes

.eslintignore, .eslintrc.js, .gitignore, dist/assertions/elementRegresses.js, dist/commands/captureElementScreenshot.js, dist/helpers.js, dist/reporting/reporter.js, jest.config.js, package.json, src/assertions/elementRegresses.js, src/commands/captureElementScreenshot.js, src/helpers.js, src/reporting/reporter.js, test/helpers.test.js, yarn.lock
Added Jest to codebase and simple tests around hasProperty function. Commands added to package.json for running test and also for running with coverage report that is output in console.
=> Introduce JS unit tests

README.md, dist/assertions/elementRegresses.js, dist/commands/captureElementScreenshot.js, dist/index.js, src/assertions/elementRegresses.js, src/commands/captureElementScreenshot.js, src/index.js
This PR creates documentation for the command and assertion, it also normalises parameter positions for both and includes additional checks to prevent invalid input from borking the process.
=> Create documentation for command an assertion use

README.md, src/assertions/elementRegresses.js
Have documented this behaviour
Fixes issue #24
=> Give assertion default selector of body

src/assertions/elementRegresses.js
=> HOTFIX isNan is not a function now isNaN

dist/assertions/elementRegresses.js, dist/reporting/views/index.handlebars, src/reporting/views/index.handlebars
- Minor refactor to toggle content switches functionality to show/hide relevant sections and content
- Implemented show/hide checkbox for skipped sections
- Refactor css selector usage from :not
- Added missing elementRegresses dist file from yarn build
=> Improvements to toggle content switches

dist/reporting/results-formatter.js, dist/reporting/views/index.handlebars, src/reporting/results-formatter.js, src/reporting/views/index.handlebars
* Approval only required on regression failures
* Modified messages to remove unicode output - unicode generated for terminal colours
=> Improvements to reported output

.gitignore, .vscode/launch.json, src/assertions/elementRegresses.js, src/helpers.js, src/index.js, test/assertions/elementRegresses.test.js, test/helpers.test.js, test/index.test.js
When threshold is below 0 or above 1 then user is informed that the value is outside the required range
=> Improvement to invalid threshold user feedback

.travis.yml
This commit adds travis support, for the moment it will test against node
versions 8 and 10.
=> ci: add travis integration

dist/reporting/results-formatter.js, dist/reporting/views/index.handlebars, example/tests/groupB/basicTest.js, example/tests/groupB/subB/basicSubTest.js, example/tests/groupB/subB/basicSubTest2.js, src/reporting/results-formatter.js, src/reporting/views/index.handlebars
* Update to results formatter
* failing tests added to demo change
* Updated report to reflect the changes
=> Display regression screenshots on passing regression tests

dist/reporting/views/index.handlebars, src/reporting/views/index.handlebars
* prevent reload on approval.
* add close button to report.
=> prevent reload on approval. add close button to report

__mocks__/jimp.js, dist/commands/captureElementScreenshot.js, dist/helpers.js, dist/regression/processImages.js, dist/regression/promises/elementSize.js, dist/regression/promises/execute.js, dist/regression/promises/jimpifyScreenshots.js, dist/regression/promises/locationInView.js, dist/reporting/results-formatter.js, src/commands/captureElementScreenshot.js, src/helpers.js, src/regression/processImages.js, src/regression/promises/elementSize.js, src/regression/promises/execute.js, src/regression/promises/jimpifyScreenshots.js, src/regression/promises/locationInView.js, src/reporting/results-formatter.js, test/assertions/elementRegresses.test.js, test/commands/captureElementScreenshot.test.js, test/regression/processImages.test.js, test/regression/promises/elementSize.test.js, test/regression/promises/execute.test.js, test/regression/promises/jimpifyScreenshots.test.js, test/regression/promises/locationInView.test.js, test/reporting/results-formatter.test.js
Increase test coverage on src.
Includes some refactoring, primarily touching captureElementScreenshot,
helpers and reporting components.
=> test: Extend test coverage of src

dist/reporting/results-formatter.js, dist/reporting/views/index.handlebars, example/yarn.lock, package.json, src/reporting/results-formatter.js, src/reporting/views/index.handlebars, test/reporting/results-formatter.test.js, yarn.lock
Updated reporter to display errors on the 'Show all' and 'Errors' tabs
=> Display error on report

example/tests/groupA/basicTest.js
add this so we can easily test VP-4152 - amend results-formatter to use filename not selector
=> updated basic example test to check results formatter uses filename

dist/reporting/server.js, dist/reporting/views/index.handlebars, example/yarn.lock, package.json, src/reporting/server.js, src/reporting/views/index.handlebars, yarn.lock
Should help mitigate the issues described in #55
=> feat: add modal imager viewer support to report

dist/reporting/reporter.js, dist/reporting/server.js, src/reporting/server.js
=> handle server error in express

dist/reporting/server.js, package.json, src/reporting/server.js, yarn.lock
add normalize-paths dependency
fixes paths in express server
=> fix: Normailse paths in express server

dist/assertions/elementRegresses.js, package.json, src/assertions/elementRegresses.js
Thresholds are being handled incorrectly. This should ensure they aren't confused with messages. Also includes previously unbuild changes.
=> Fix issue with displaying screenshots
